name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MCO_LOG_LEVEL: warn

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci install
      - name: Test
        run: npm test
      - name: Download Codecov
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pip install codecov-cli  
      - name: Run Codecov
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecovcli create-commit
          codecovcli create-report
          codecovcli do-upload

      - uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ matrix.node-version }}
          path: coverage
